language: python

python:
  . 2.7
  - 3.6

cache:
  pip:
  apt:
  directories:
    - .tox

env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py36-django18
  - TOX_ENV=py36-django19
  - TOX_ENV=py36-django110

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq $APT

after_failure:
  - cat /home/travis/.pip/pip.log

after_success:
  - coveralls

install:
  - pip install pip wheel
  - pip install -q coveralls flake8 tox

script:
  - env | sort
  - tox -e $TOX_ENV
  - flake8 --show-source --max-line-length=80 --exclude=.tox,docs,inline_media/tests/settings,inline_media/__init__.py,inline_media/migrations inline_media/

