# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('inline_media', '0002_auto_20150825_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureset',
            name='order',
            field=models.CharField(blank=True, help_text='Establish pictures order by typing the comma separated list of their picture IDs.', max_length=512, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
